### ISSUE TITLE
Unified Error Handling Strategy

### ISSUE THREAD

**Issue by jeremylt** [jeremiah-corrado/fem_2d#3]
Yohann has covered many good design points, so I will focus on some more Rust specific implementation details.

In my experience, Rust users tend to expect error handling to work like:
```rust
pub fn this_fn_could_fail(some_arg: usize) -> MyCrateResult<usize> {
  // ? to propagate possible error from function call
  let some_intermediate_value = other_possible_to_fail(some_arg)?;
  Ok(42 * some_intermediate_value)
}
```

You seem to have a mix of error handling strategies in this crate that isn't immediately clear to me. The `unwrap()` method is called on intermediate results from function calls internally that seem like they could fail.

I recommend a) unifying your error handling strategy or b) documenting why you have different error handling strategies in different parts of the codebase.

Similarly, in the paper, I would update the example to use `?` instead of `.unwrap()` - from what I've seen, its currently a bit more idiomatic for the main driver function to return `Result<()>`.

**Comment by jeremiah-corrado** [comment]
Hi @jeremylt, thank you again for the feedback! 

I've made some updates to the error handling strategy, particularly in the *hp*-refinement API.  The [Mesh documentation](https://docs.rs/fem_2d/latest/fem_2d/fem_domain/domain/mesh/struct.Mesh.html) now has a clear list of which errors could occur for each of these methods. 

I also modified the paper to hopefully explain my thinking behind the error handling strategy a little bit better. The examples have been updated to use the `?` operator.

W.R.T your [comment](https://github.com/openjournals/joss-reviews/issues/4172#issuecomment-1108691106) in the review discussion, I have to disagree with your notion that all the methods should return a `Result<(), Error>` in order to prevent future breaking changes. In some cases, the method is designed not to err *by definition*, and thus I think it is actually more confusing to encode that possibility into the function header. For example, [global_h_refinement](https://docs.rs/fem_2d/latest/fem_2d/fem_domain/domain/mesh/struct.Mesh.html#method.global_h_refinement) only applies a refinement to the `Elems` that are eligible for *h*-refinement. Thus, *by defnintion* it will never run into any of the `HRefError` cases (unless there is a bug in the implementaiton of Mesh, in which case a `panic` is appropriate). As such, I think a `Result<(), HRefError>` return-type would contradict the definition of the method, which is confusing for users. 

Lastly, some new Error types were created for a few other structures and functions in the library, where I had previously been returning a formatted String as the Error Type.

**Comment by jeremylt** [comment]
Like I said in the other thread, I'm personally uncomfortable designing code that is coupled in that way. I understand that you don't want to change the design and you have reasons why you don't. I think documenting the assumptions that must be respected in future development related to the revelant 'impossible to fail' functions would be enough to close this issue. Future contributors who aren't you may not find these assumptions obvious.

**Comment by jeremiah-corrado** [comment]
Ok that makes sense. I just made those documentation additions to mesh.rs
